const express = require("express")
const { default: mongoose } = require("mongoose")
const Address = require("./Routes/Address.route")
const AddressModel = require("./Schemas/Address")
const cartModel = require("./Schemas/Cart.model")
const ProdModel = require("./Schemas/Prods.model")
const Cartroute = require("./Routes/Cart.route")
const Productsroute = require("./Routes/Productrouter")
const cors=require("cors")
const app = express()
app.use(express.json())
app.use(cors())
// Note: added routes and end points
app.use("/address",Address)
app.use("/cart",Cartroute)
app.use("/products",Productsroute)

mongoose.connect("mongodb+srv://tendercuts:tendercuts@cluster0.hyunvkz.mongodb.net/TenderCutsMain").then(() => app.listen(8080, () => console.log("server satrted"))).catch(er => console.log(er))
